// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu3hIMdokj2M58DXFMsneHW1PKiYS_Mg0',
    appId: '1:340862364431:web:d0ead133c241760454ec7a',
    messagingSenderId: '340862364431',
    projectId: 'collegeapp-18dde',
    authDomain: 'collegeapp-18dde.firebaseapp.com',
    storageBucket: 'collegeapp-18dde.firebasestorage.app',
    measurementId: 'G-YQD896SGQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCknN1CNNEAZBl3BwkXQ5JCHKxXO7Hnc1k',
    appId: '1:340862364431:android:07144e870880052354ec7a',
    messagingSenderId: '340862364431',
    projectId: 'collegeapp-18dde',
    storageBucket: 'collegeapp-18dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_sJCG28FvGtuwxWGwra5Kz8BCusUeW_Q',
    appId: '1:340862364431:ios:0688c375fae1a05054ec7a',
    messagingSenderId: '340862364431',
    projectId: 'collegeapp-18dde',
    storageBucket: 'collegeapp-18dde.firebasestorage.app',
    iosClientId: '340862364431-55k1isonvonhe6dtckk360vlesvmbgab.apps.googleusercontent.com',
    iosBundleId: 'com.classified.collegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_sJCG28FvGtuwxWGwra5Kz8BCusUeW_Q',
    appId: '1:340862364431:ios:0688c375fae1a05054ec7a',
    messagingSenderId: '340862364431',
    projectId: 'collegeapp-18dde',
    storageBucket: 'collegeapp-18dde.firebasestorage.app',
    iosClientId: '340862364431-55k1isonvonhe6dtckk360vlesvmbgab.apps.googleusercontent.com',
    iosBundleId: 'com.classified.collegeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu3hIMdokj2M58DXFMsneHW1PKiYS_Mg0',
    appId: '1:340862364431:web:755a3ef38613091c54ec7a',
    messagingSenderId: '340862364431',
    projectId: 'collegeapp-18dde',
    authDomain: 'collegeapp-18dde.firebaseapp.com',
    storageBucket: 'collegeapp-18dde.firebasestorage.app',
    measurementId: 'G-HNKGKZH12J',
  );
}
